-- ============================================================
-- PropTrack AI — Initial Schema
-- V1__initial_schema.sql
-- ============================================================

-- USERS
CREATE TABLE users (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email       VARCHAR(255) NOT NULL UNIQUE,
    password    VARCHAR(255) NOT NULL,
    full_name   VARCHAR(255) NOT NULL,
    role        VARCHAR(50)  NOT NULL DEFAULT 'OWNER',  -- OWNER | PARTNER
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- REFRESH TOKENS
CREATE TABLE refresh_tokens (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token       VARCHAR(512) NOT NULL UNIQUE,
    expires_at  TIMESTAMPTZ NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- PROPERTIES
CREATE TABLE properties (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name                VARCHAR(255) NOT NULL,
    address             TEXT NOT NULL,
    city                VARCHAR(100) NOT NULL,
    state               VARCHAR(100) NOT NULL,
    area_sqft           DECIMAL(10,2),
    purchase_price      DECIMAL(15,2) NOT NULL,
    purchase_date       DATE NOT NULL,
    possession_date     DATE NOT NULL,            -- 2030 target
    builder_name        VARCHAR(255),
    current_valuation   DECIMAL(15,2),            -- latest manual estimate
    status              VARCHAR(50) NOT NULL DEFAULT 'UNDER_CONSTRUCTION',
    created_by          UUID NOT NULL REFERENCES users(id),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- PROPERTY PARTNERS (who co-owns the property)
CREATE TABLE property_partners (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    property_id     UUID NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
    user_id         UUID NOT NULL REFERENCES users(id),
    share_percent   DECIMAL(5,2) NOT NULL DEFAULT 50.00,
    joined_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(property_id, user_id)
);

-- LOANS
CREATE TABLE loans (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    property_id         UUID NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
    bank_name           VARCHAR(255) NOT NULL,
    sanction_amount     DECIMAL(15,2) NOT NULL,
    disbursed_amount    DECIMAL(15,2) NOT NULL DEFAULT 0,
    interest_rate       DECIMAL(5,3) NOT NULL,          -- annual % e.g. 8.750
    tenure_months       INTEGER NOT NULL,
    emi_amount          DECIMAL(15,2),                  -- calculated or set
    start_date          DATE NOT NULL,
    loan_account_number VARCHAR(100),
    status              VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- EMI SCHEDULE (generated by LoanService on loan creation)
CREATE TABLE emi_schedule (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    loan_id             UUID NOT NULL REFERENCES loans(id) ON DELETE CASCADE,
    emi_number          INTEGER NOT NULL,
    due_date            DATE NOT NULL,
    emi_amount          DECIMAL(15,2) NOT NULL,
    principal_component DECIMAL(15,2) NOT NULL,
    interest_component  DECIMAL(15,2) NOT NULL,
    balance_after       DECIMAL(15,2) NOT NULL,
    status              VARCHAR(50) NOT NULL DEFAULT 'PENDING',  -- PENDING | PAID | OVERDUE
    paid_date           DATE,
    paid_amount         DECIMAL(15,2),
    UNIQUE(loan_id, emi_number)
);

-- PAYMENTS (partner contributions — tracked separately from EMIs)
CREATE TABLE payments (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    property_id     UUID NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
    paid_by         UUID NOT NULL REFERENCES users(id),
    amount          DECIMAL(15,2) NOT NULL,
    payment_date    DATE NOT NULL,
    payment_type    VARCHAR(50) NOT NULL,            -- EMI_SHARE | DOWN_PAYMENT | PREPAYMENT | OTHER
    utr_number      VARCHAR(100),                   -- bank transfer reference
    bank_name       VARCHAR(100),
    notes           TEXT,
    screenshot_url  TEXT,                           -- Supabase Storage URL
    ocr_processed   BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- VALUATION HISTORY (manual checkpoints over time)
CREATE TABLE valuation_history (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    property_id     UUID NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
    valuation_date  DATE NOT NULL,
    amount          DECIMAL(15,2) NOT NULL,
    source          VARCHAR(100),                   -- 'MANUAL' | 'BROKER_ESTIMATE' etc.
    notes           TEXT,
    created_by      UUID NOT NULL REFERENCES users(id),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- DOCUMENTS
CREATE TABLE documents (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    property_id     UUID NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
    doc_type        VARCHAR(100) NOT NULL,          -- SALE_AGREEMENT | ALLOTMENT_LETTER | SANCTION_LETTER | RECEIPT | OTHER
    file_name       VARCHAR(255) NOT NULL,
    storage_url     TEXT NOT NULL,                  -- Supabase Storage URL
    file_size_bytes BIGINT,
    mime_type       VARCHAR(100),
    ai_summary      TEXT,                           -- Claude-extracted summary
    ai_processed    BOOLEAN NOT NULL DEFAULT FALSE,
    uploaded_by     UUID NOT NULL REFERENCES users(id),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- NOTIFICATION PREFERENCES
CREATE TABLE notification_preferences (
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id                 UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE UNIQUE,
    emi_due_reminder        BOOLEAN NOT NULL DEFAULT TRUE,
    payment_confirmed       BOOLEAN NOT NULL DEFAULT TRUE,
    partner_imbalance_alert BOOLEAN NOT NULL DEFAULT TRUE,
    monthly_summary         BOOLEAN NOT NULL DEFAULT TRUE,
    annual_report           BOOLEAN NOT NULL DEFAULT TRUE,
    imbalance_threshold     DECIMAL(15,2) NOT NULL DEFAULT 5000.00,
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- AUDIT LOG (immutable record of important actions)
CREATE TABLE audit_log (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID REFERENCES users(id),
    entity_type VARCHAR(100) NOT NULL,
    entity_id   UUID,
    action      VARCHAR(100) NOT NULL,
    details     JSONB,
    ip_address  VARCHAR(50),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- INDEXES
-- ============================================================
CREATE INDEX idx_payments_property_id   ON payments(property_id);
CREATE INDEX idx_payments_paid_by       ON payments(paid_by);
CREATE INDEX idx_payments_payment_date  ON payments(payment_date DESC);
CREATE INDEX idx_emi_schedule_loan_id   ON emi_schedule(loan_id);
CREATE INDEX idx_emi_schedule_due_date  ON emi_schedule(due_date);
CREATE INDEX idx_emi_schedule_status    ON emi_schedule(status);
CREATE INDEX idx_documents_property_id  ON documents(property_id);
CREATE INDEX idx_audit_log_entity       ON audit_log(entity_type, entity_id);
CREATE INDEX idx_audit_log_user_id      ON audit_log(user_id);
CREATE INDEX idx_valuation_property_id  ON valuation_history(property_id, valuation_date DESC);
CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens(user_id);